[core]
reloadable = false
order = -10

[package]
version = "0.0.2"
category = "Simulation"
authors = ["Toni-SM"]
title = "USD Add-on schema"
description="USD Add-on schema"
repository = ""
keywords = ["add-on", "usd", "schema"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]
"omni.usd.schema.isaac" = {}

[[python.module]]
name = "omni.add_on.RosBridgeSchema"

[[python.module]]
name = "omni.add_on.RosControlBridgeSchema"
