[core]
reloadable = false
order = -10

[package]
version = "0.0.3"
category = "Simulation"
feature = false
app = false
authors = ["Toni-SM"]
title = "USD schemas (semu namespace)"
description="USD schema for external extensions (semu namespace)"
repository = "https://github.com/Toni-SM/semu.usd.schemas"
keywords = ["Schema", "ROS"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[package.target]
config = ["release"]
platform = ["linux-*"]
python = ["*"]

[dependencies]
"omni.usd.schema.isaac" = {}

[[python.module]]
name = "semu.usd.schemas.RosBridgeSchema"

[[python.module]]
name = "semu.usd.schemas.RosControlBridgeSchema"
